name: Update database daily

on:
  schedule:
    # Runs at 12:01 PM UTC
    - cron: '1 12 * * *'
  workflow_dispatch:

jobs:
  run-python-script:
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9.6' 

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run the script
      run: python update_db.py
